export const Users = [
  {
    id: 1,
    profilepicture: "post/pis2.jpg",
    username: "Neelam Bhatia",
  },
  {
    id: 2,
    profilepicture: "person/pic2.jpg",
    username: "selena",
  },
  {
    id: 3,
    profilepicture: "person/pic3.jpg",
    username: "palak",
  },
  {
    id: 4,
    profilepicture: "person/pic4.jpg",
    username: "tejaswi",
  },
  {
    id: 5,
    profilepicture: "person/pic11.jpg",
    username: "justin",
  },
  {
    id: 6,
    profilepicture: "person/pic8.jpg",
    username: "gyan",
  },
  {
    id: 7,
    profilepicture: "person/pic9.jpg",
    username: "Anant",
  },
  {
    id: 8,
    profilepicture: "person/pic18.jpg",
    username: "Ayan",
  },
  {
    id: 9,
    profilepicture: "person/pic12.jpg",
    username: "monalisa",
  },
  {
    id: 10,
    profilepicture: "person/pic6.jpg",
    username: "panu",
  },
  {
    id: 11,
    profilepicture: "person/pic14.jpg",
    username: "shree",
  },
  {
    id: 12,
    profilepicture: "person/pic17.jpg",
    username: "ayan",
  },
  {
    id: 13,
    profilepicture: "person/pic16.jpg",
    username: "sandy",
  },
  {
    id: 14,
    profilepicture: "person/pic15.jpg",
    username: "sid",
  },
  {
    id: 15,
    profilepicture: "person/pic10.jpg",
    username: "mona",
  },
];

export const Postdata = [
  {
    id: 1,
    desc: "Enjoy summer vaccations with buddies",
    photo: "post/pis7.jpg",
    date: "5 mins ago",
    userid: 1,
    like: 50,
    Comment: 10,
  },
  {
    id: 2,
    desc: "Spent some lovable time with bestie",
    photo: "post/pis4.jpg",
    date: "8 mins ago",
    userid: 2,
    like: 35,
    Comment: 12,
  },
  {
    id: 3,
    desc: "Love for All, Hatred for None",
    photo: "post/pis6.jpg",
    date: "10 mins ago",
    userid: 3,
    like: 45,
    Comment: 15,
  },
  {
    id: 4,
    desc: "Joyfull party at home with family",
    photo: "post/pis5.jpg",
    date: "8 hour ago",
    userid: 4,
    like: 55,
    Comment: 20,
  },
  {
    id: 5,
    desc: "Beauty of Nature is not definable",
    photo: "post/pis3.jpg",
    date: "12 hour ago",
    userid: 5,
    like: 25,
    Comment: 1,
  },
  {
    id: 6,
    desc: "The day of tea with my charm",
    photo: "post/pis1.jpg",
    date: "12 hour ago",
    userid: 6,
    like: 38,
    Comment: 8,
  },
  {
    id: 7,
    desc: "Rock the party",
    photo: "post/pis8.jpg",
    date: "1 day ago",
    userid: 7,
    like: 42,
    Comment: 5,
  },
  {
    id: 8,
    desc: "Chill with mains ",
    photo: "post/pis9.jpg",
    date: "1 day ago",
    userid: 8,
    like: 48,
    Comment: 7,
  },
  {
    id: 9,
    desc: "My lil lil Bro",
    photo: "post/pis10.jpg",
    date: "1 day ago",
    userid: 9,
    like: 22,
    Comment: 18,
  },
  {
    id: 10,
    desc: "Some old moments are really give smile on face",
    photo: "post/pis11.jpg",
    date: "2 day ago",
    userid: 10,
    like: 20,
    Comment: 16,
  },
  {
    id: 11,
    desc: "I am the cute one.",
    photo: "post/pis12.jpg",
    date: "2 day ago",
    userid: 11,
    like: 15,
    Comment: 13,
  },
  {
    id: 12,
    desc: "Fregranse  of flowersce are really aswm",
    photo: "post/pis13.jpg",
    date: "2 day ago",
    userid: 12,
    like: 47,
    Comment: 21,
  },
  {
    id: 13,
    desc: "Love for All, Hatred for None",
    photo: "post/pis17.jpg",
    date: "2 day ago",
    userid: 13,
    like: 65,
    Comment: 30,
  },
  {
    id: 14,
    desc: "Hey! I am cute Chicken ",
    photo: "post/pis15.jpg",
    date: "1 week ago",
    userid: 14,
    like: 58,
    Comment: 24,
  },
  {
    id: 15,
    desc: "Silent roads",
    photo: "post/pis16.jpg",
    date: "1 week ago",
    userid: 15,
    like: 12,
    Comment: 3,
  },
];
